#!/usr/bin/env python3

import requests

data = """
{
   "class": "uk.gov.gchq.gaffer.operation.impl.get.GetAllElements"
}
"""

url = 'http://localhost:8080/rest/v1/graph/doOperation/get/elements/all'

response = requests.post(url, data,
                         headers={'content-type': 'application/json'})

print("Status:",response.status_code)
print(response.text)

